# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-Modem-GSM
version:      0.2
version_from: lib/Device/Modem/GSM.pm
installdirs:  site
requires:
    Device::Modem:                 1.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
